site_name: Student Performance
nav:
    - Home: index.md
    - Git Hub and code setup: githubsetup.md
    - Logging and exception handling: logexception.md
    - Exploratory data analysis: eda.md
    - Model training: mdltraining.md
    - Data ingestion: dataingestion.md
    - Data transforming (pipelines): datatranform.md
    - Model Training and evaluation: mdltraineval.md
    - Hyperparameter tuning: hyperparam.md
    - Prediction using Flask: flaskpred.md
theme: readthedocs