site_name: Student Performance
nav:
    - Home: index.md
    - GitHub and code setup: githubsetup.md
    - Logging and exception handling: logexception.md
    - Data ingestion: dataingestion.md
    - Data transformation (pipelines): datatranform.md
    - Model training and evaluation: mdltraineval.md
    - Prediction using Flask: flaskpred.md
theme: readthedocs